package ru.neoflex.emf.bazi

import ru.neoflex.emf.bazi.natalChart.NatalChart
import ru.neoflex.emf.bazi.natalChart.InputParams
import ru.neoflex.emf.bazi.calendar.Calendar
import ru.neoflex.emf.bazi.calendar.Year
import ru.neoflex.emf.bazi.calendar.CalendarFactory
import ru.neoflex.emf.bazi.natalChart.NatalChartFactory
import ru.neoflex.emf.bazi.natalChart.Pillar

rule "TEST Set Year Pillar"
when
    $natalChart: NatalChart($inputParams: inputParams, inputParams != null, year == null)
    $calendar: Calendar($year: year)
    $currentYear: Year(name == $inputParams.year, year != null) from $year
then
    Pillar year = NatalChartFactory.eINSTANCE.createPillar();
    year.setSky($currentYear.getYear().getSky());
    year.setEarth($currentYear.getYear().getEarth());
    $natalChart.setYear(year);
    update($natalChart);
end;

