package ru.neoflex.emf.bazi

import ru.neoflex.emf.bazi.natalChart.NatalChart
import ru.neoflex.emf.bazi.natalChart.InputParams
import ru.neoflex.emf.bazi.calendar.Calendar
import ru.neoflex.emf.bazi.calendar.Year
import ru.neoflex.emf.bazi.calendar.CalendarFactory
import ru.neoflex.emf.bazi.calendar.BaZiDate
import ru.neoflex.emf.bazi.natalChart.NatalChartFactory
import ru.neoflex.emf.bazi.natalChart.Pillar
import ru.neoflex.emf.bazi.natalChart.Zoo
import ru.neoflex.emf.bazi.natalChart.Elements
import java.util.Arrays
import java.util.List
import ru.neoflex.emf.restserver.DBServerSvc
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.ObjectWriter

function Pillar createYearPillar(BaZiDate baZiDate) {
    Pillar pillar = NatalChartFactory.eINSTANCE.createPillar();

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyIndex = baZiDate.getChineseYear() % 10 + 1;
    Elements sky = elements.get(skyIndex);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthIndex = baZiDate.getChineseYear() % 12 + 1;
    Zoo earth = zoo.get(earthIndex);

    pillar.setSky(sky);
    pillar.setEarth(earth);
    return pillar;
}

rule "TEST Set Year Pillar"
when
    $natalChart: NatalChart($inputParams: inputParams, inputParams != null)
    $baZiDate: BaZiDate()
then
    Pillar year = createYearPillar($baZiDate);
    $natalChart.setYear(year);
    update($natalChart);
end;

