package ru.neoflex.emf.bazi

import ru.neoflex.emf.bazi.natalChart.NatalChart
import ru.neoflex.emf.bazi.natalChart.InputParams
import ru.neoflex.emf.bazi.calendar.Calendar
import ru.neoflex.emf.bazi.calendar.Year
import ru.neoflex.emf.bazi.calendar.CalendarFactory
import ru.neoflex.emf.bazi.calendar.BaZiDate
import ru.neoflex.emf.bazi.natalChart.NatalChartFactory
import ru.neoflex.emf.bazi.natalChart.Pillar
import ru.neoflex.emf.bazi.natalChart.Zoo
import ru.neoflex.emf.bazi.natalChart.Elements
import java.util.Arrays
import java.util.List
import ru.neoflex.emf.restserver.DBServerSvc
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.ObjectWriter
import ru.neoflex.emf.bazi.natalChart.God
import ru.neoflex.emf.bazi.natalChart.Conclusions
import ru.neoflex.emf.bazi.natalChart.Result
import org.eclipse.emf.common.util.EList


function NatalChart addPersonalityElement(NatalChart natalChart, Conclusions conclusions) {
    Pillar day = natalChart.getDay();
    Elements personalityElement = day.getSky();
    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyDayIndex = elements.indexOf(personalityElement);

    Integer code = skyDayIndex;
    Result result = NatalChartFactory.eINSTANCE.createResult();
    for (Result res : conclusions.getResults()) {
                    if (res.getCode().equals(code)) {
                        result.setCode(code);
                        result.setTitle(res.getTitle());
                        result.setDescription(res.getDescription());
                    }
                }

    natalChart.getConclusions().getResults().add(result);
    return natalChart;
}

rule "Create All Conclusions"
when
    $natalChart: NatalChart(day != null)
    not Conclusions()
then
    Conclusions conclusions = NatalChartFactory.eINSTANCE.createConclusions();
    insert(conclusions);
end;

rule "Set Conclusion in NatalChart"
no-loop true
when
    $natalChart: NatalChart(day != null)
then
    Conclusions conclusions = NatalChartFactory.eINSTANCE.createConclusions();
    $natalChart.setConclusions(conclusions);
    update($natalChart);
end;

rule "Set Personality Element in NatalChart"
no-loop true
when
    $natalChart: NatalChart(day != null)
    $conclusions: Conclusions(results != null)
then
    addPersonalityElement($natalChart, $conclusions);
    update($natalChart);
end;
