package ru.neoflex.emf.bazi

import ru.neoflex.emf.bazi.natalChart.NatalChart
import ru.neoflex.emf.bazi.natalChart.InputParams
import ru.neoflex.emf.bazi.calendar.Calendar
import ru.neoflex.emf.bazi.calendar.Year
import ru.neoflex.emf.bazi.calendar.CalendarFactory
import ru.neoflex.emf.bazi.calendar.BaZiDate
import ru.neoflex.emf.bazi.natalChart.NatalChartFactory
import ru.neoflex.emf.bazi.natalChart.Pillar
import ru.neoflex.emf.bazi.natalChart.Zoo
import ru.neoflex.emf.bazi.natalChart.Elements
import java.util.Arrays
import java.util.List
import ru.neoflex.emf.restserver.DBServerSvc
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.ObjectWriter
import ru.neoflex.emf.bazi.natalChart.God
import ru.neoflex.emf.bazi.natalChart.Conclusions
import ru.neoflex.emf.bazi.natalChart.Result

function Conclusions addPersonalityElement(NatalChart natalChart, Conclusions conclusions) {
    Pillar day = natalChart.getDay();
    Elements personalityElement = day.getSky();
    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyDayIndex = elements.indexOf(personalityElement);

    String description = skyDayIndex.toString();

    return conclusions;
}

rule "Create Conclusions"
when
    $natalChart: NatalChart(day != null)
    not Conclusions()
then
    Conclusions conclusions = NatalChartFactory.eINSTANCE.createConclusions();
    $natalChart.setConclusions(conclusions);
    insert(conclusions);
end;

rule "Set Conclusion Personality Element"
no-loop true
when
    $conclusions: Conclusions()
    $natalChart: NatalChart(day != null)
    $baZiDate: BaZiDate(day != null)
then
    addPersonalityElement($natalChart, $conclusions);
    update($conclusions);
end;
