package ru.neoflex.emf.bazi

import ru.neoflex.emf.bazi.natalChart.NatalChart
import ru.neoflex.emf.bazi.natalChart.Pillar
import ru.neoflex.emf.bazi.natalChart.Zoo
import ru.neoflex.emf.bazi.natalChart.Elements
import java.util.Arrays
import java.util.List
import ru.neoflex.emf.bazi.spirit.Spirit

function Pillar addSpiritAngel(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           (skyElementIndex == 1 || skyElementIndex == 5 || skyElementIndex == 7) && (earthPillarIndex == 2 || earthPillarIndex == 8)
           ||
                   (skyElementIndex == 2 || skyElementIndex == 6) && (earthPillarIndex == 1 || earthPillarIndex == 9)
                   ||
                       (skyElementIndex == 3 || skyElementIndex == 4) && (earthPillarIndex == 10 || earthPillarIndex == 12)
                       ||
                           skyElementIndex == 8 && (earthPillarIndex == 3 || earthPillarIndex == 7)
                           ||
                                (skyElementIndex == 9 || skyElementIndex == 10) && (earthPillarIndex == 4 || earthPillarIndex == 6);


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelTaiChi(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           (skyElementIndex == 1 || skyElementIndex == 2) && (earthPillarIndex == 1 || earthPillarIndex == 7)
           ||
                   (skyElementIndex == 3 || skyElementIndex == 4) && (earthPillarIndex == 4 || earthPillarIndex == 10)
                   ||
                       (skyElementIndex == 5 || skyElementIndex == 6) && (earthPillarIndex == 2 || earthPillarIndex == 5 || earthPillarIndex == 8 || earthPillarIndex == 11)
                       ||
                           (skyElementIndex == 7 || skyElementIndex == 8) && (earthPillarIndex == 3 || earthPillarIndex == 12)
                           ||
                                (skyElementIndex == 9 || skyElementIndex == 10) && (earthPillarIndex == 6 || earthPillarIndex == 9);


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelPersonalLife(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 3
           ||
                   skyElementIndex == 2 && (earthPillarIndex == 2 || earthPillarIndex == 12)
                   ||
                       skyElementIndex == 3 && (earthPillarIndex == 1 || earthPillarIndex == 11)
                       ||
                           skyElementIndex == 4 && earthPillarIndex == 10
                           ||
                                skyElementIndex == 5 && earthPillarIndex == 9
                                ||
                                    skyElementIndex == 6 && earthPillarIndex == 8
                                    ||
                                        skyElementIndex == 7 && earthPillarIndex == 7
                                        ||
                                            skyElementIndex == 8 && earthPillarIndex == 6
                                            ||
                                                skyElementIndex == 9 && earthPillarIndex == 5
                                                ||
                                                    skyElementIndex == 10 && earthPillarIndex == 4;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelHeavenlyKitchen(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 6
           ||
                   skyElementIndex == 2 && earthPillarIndex == 7
                   ||
                       skyElementIndex == 3 && (earthPillarIndex == 5 || earthPillarIndex == 11)
                       ||
                           skyElementIndex == 4 && (earthPillarIndex == 2 || earthPillarIndex == 8)
                           ||
                                skyElementIndex == 5 && earthPillarIndex == 9
                                ||
                                    skyElementIndex == 6 && earthPillarIndex == 10
                                    ||
                                        skyElementIndex == 7 && earthPillarIndex == 12
                                        ||
                                            skyElementIndex == 8 && earthPillarIndex == 1
                                            ||
                                                skyElementIndex == 9 && earthPillarIndex == 3
                                                ||
                                                    skyElementIndex == 10 && earthPillarIndex == 4;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelStateStamps(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 11
           ||
                   skyElementIndex == 2 && earthPillarIndex == 12
                   ||
                       (skyElementIndex == 3 || skyElementIndex == 5 ) && earthPillarIndex == 2
                       ||
                           (skyElementIndex == 4 || skyElementIndex == 6 ) && earthPillarIndex == 3
                           ||
                                skyElementIndex == 7 && earthPillarIndex == 5
                                ||
                                    skyElementIndex == 8 && earthPillarIndex == 6
                                    ||
                                        skyElementIndex == 9 && earthPillarIndex == 8
                                        ||
                                            skyElementIndex == 10 && earthPillarIndex == 9;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelHeavenlyPower(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 10
           ||
                   skyElementIndex == 2 && earthPillarIndex == 9
                   ||
                       skyElementIndex == 3 && earthPillarIndex == 1
                       ||
                           skyElementIndex == 4 && earthPillarIndex == 12
                           ||
                                skyElementIndex == 5 && earthPillarIndex == 4
                                ||
                                    skyElementIndex == 6 && earthPillarIndex == 3
                                    ||
                                        skyElementIndex == 7 && earthPillarIndex == 7
                                        ||
                                            skyElementIndex == 8 && earthPillarIndex == 6
                                            ||
                                                skyElementIndex == 9 && ( earthPillarIndex == 2 || earthPillarIndex == 8 )
                                                ||
                                                    skyElementIndex == 10 && ( earthPillarIndex == 5 || earthPillarIndex == 11 );


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelHeavenlyOfficer(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 8
           ||
                   skyElementIndex == 2 && earthPillarIndex == 5
                   ||
                       skyElementIndex == 3 && earthPillarIndex == 6
                       ||
                           skyElementIndex == 4 && earthPillarIndex == 10
                           ||
                                skyElementIndex == 5 && earthPillarIndex == 11
                                ||
                                    skyElementIndex == 6 && earthPillarIndex == 4
                                    ||
                                        skyElementIndex == 7 && ( earthPillarIndex == 2 || earthPillarIndex == 12 )
                                        ||
                                            skyElementIndex == 8 && earthPillarIndex == 9
                                            ||
                                                skyElementIndex == 9 && earthPillarIndex == 3
                                                ||
                                                    skyElementIndex == 10 && earthPillarIndex == 7;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelLiterature(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           skyElementIndex == 1 && earthPillarIndex == 6
           ||
                   skyElementIndex == 2 && earthPillarIndex == 7
                   ||
                       (skyElementIndex == 3 || skyElementIndex == 5 ) && earthPillarIndex == 9
                       ||
                           (skyElementIndex == 4 || skyElementIndex == 6 ) && earthPillarIndex == 10
                           ||
                                skyElementIndex == 7 && earthPillarIndex == 12
                                ||
                                    skyElementIndex == 8 && earthPillarIndex == 1
                                    ||
                                        skyElementIndex == 9 && earthPillarIndex == 3
                                        ||
                                            skyElementIndex == 10 && earthPillarIndex == 4;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritAngelCorrectSize(Pillar pillar, Elements skyElement, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyElementIndex = elements.indexOf(skyElement);

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
           (skyElementIndex == 1 || skyElementIndex == 3 || skyElementIndex == 5 ) && earthPillarIndex == 6
           ||
                   (skyElementIndex == 2 || skyElementIndex == 4 || skyElementIndex == 6 ) && earthPillarIndex == 8
                   ||
                       (skyElementIndex == 7 || skyElementIndex == 9 ) && earthPillarIndex == 12
                       ||
                           (skyElementIndex == 8 || skyElementIndex == 10 ) && earthPillarIndex == 2;


    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritHeavenlyVirtue(Pillar pillar, Zoo earthZoo, Spirit spirit) {

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthZooIndex = zoo.indexOf(earthZoo);

    List<Elements> elements = Arrays.asList(Elements.values());
    Elements skyPillar = pillar.getSky();
    Integer skyPillarIndex = elements.indexOf(skyPillar);

    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
        earthZooIndex == 1 && earthPillarIndex == 6
        ||
            earthZooIndex == 2 && skyPillarIndex == 7
            ||
                earthZooIndex == 3 && skyPillarIndex == 4
                ||
                    earthZooIndex == 4 && earthPillarIndex == 9
                    ||
                        earthZooIndex == 5 && skyPillarIndex == 9
                        ||
                            earthZooIndex == 6 && skyPillarIndex == 8
                            ||
                                earthZooIndex == 7 && earthPillarIndex == 12
                                ||
                                    earthZooIndex == 8 && skyPillarIndex == 1
                                    ||
                                        earthZooIndex == 9 && skyPillarIndex == 10
                                        ||
                                            earthZooIndex == 10 && earthPillarIndex == 3
                                            ||
                                                earthZooIndex == 11 && skyPillarIndex == 3
                                                ||
                                                    earthZooIndex == 12 && skyPillarIndex == 2;

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritLunarVirtue(Pillar pillar, Zoo earthZoo, Spirit spirit) {

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthZooIndex = zoo.indexOf(earthZoo);

    List<Elements> elements = Arrays.asList(Elements.values());
    Elements skyPillar = pillar.getSky();
    Integer skyPillarIndex = elements.indexOf(skyPillar);

    Boolean check =
        ( earthZooIndex == 1 || earthZooIndex == 5 || earthZooIndex == 9 ) && skyPillarIndex == 9
        ||
            ( earthZooIndex == 2 || earthZooIndex == 6 || earthZooIndex == 10 ) && skyPillarIndex == 7
            ||
                ( earthZooIndex == 3 || earthZooIndex == 7 || earthZooIndex == 11 ) && skyPillarIndex == 3
                ||
                    ( earthZooIndex == 4 || earthZooIndex == 8 || earthZooIndex == 12 ) && skyPillarIndex == 1;

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritThreeMystics(Pillar pillar, Integer pillarIndex, Elements hour, Elements day, Elements month, Elements year, Spirit spirit) {

    List<Elements> elements = Arrays.asList(Elements.values());
    Integer skyHourIndex = elements.indexOf(hour);
    Integer skyDayIndex = elements.indexOf(day);
    Integer skyMonthIndex = elements.indexOf(month);
    Integer skyYearIndex = elements.indexOf(year);

    Boolean check =
        skyHourIndex == 7 && skyDayIndex == 5 && skyMonthIndex == 1 && pillarIndex != 4
        ||
            skyDayIndex == 7 && skyMonthIndex == 5 && skyYearIndex == 1 && pillarIndex != 1
            ||
                skyHourIndex == 4 && skyDayIndex == 5 && skyMonthIndex == 2 && pillarIndex != 4
                ||
                    skyDayIndex == 4 && skyMonthIndex == 5 && skyYearIndex == 2 && pillarIndex != 1
                    ||
                        skyHourIndex == 8 && skyDayIndex == 10 && skyMonthIndex == 9 && pillarIndex != 4
                        ||
                            skyDayIndex == 8 && skyMonthIndex == 10 && skyYearIndex == 9 && pillarIndex != 1;

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritHelperStar(Pillar pillar, Zoo earthZoo, Spirit spirit) {

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthZooIndex = zoo.indexOf(earthZoo);

    List<Elements> elements = Arrays.asList(Elements.values());
    Elements skyPillar = pillar.getSky();
    Integer skyPillarIndex = elements.indexOf(skyPillar);

    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
        earthZooIndex == 1 && earthPillarIndex == 6
        ||
            earthZooIndex == 2 && skyPillarIndex == 8
            ||
                earthZooIndex == 3 && skyPillarIndex == 4
                ||
                    earthZooIndex == 4 && earthPillarIndex == 9
                    ||
                        earthZooIndex == 5 && skyPillarIndex == 9
                        ||
                            earthZooIndex == 6 && skyPillarIndex == 8
                            ||
                                earthZooIndex == 7 && earthPillarIndex == 12
                                ||
                                    earthZooIndex == 8 && skyPillarIndex == 1
                                    ||
                                        earthZooIndex == 9 && skyPillarIndex == 10
                                        ||
                                            earthZooIndex == 10 && earthPillarIndex == 3
                                            ||
                                                earthZooIndex == 11 && skyPillarIndex == 3
                                                ||
                                                    earthZooIndex == 12 && skyPillarIndex == 2;

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addSpiritDragonStar(Pillar pillar, Zoo earthZoo, Spirit spirit) {

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthZooIndex = zoo.indexOf(earthZoo);

    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
        earthZooIndex == 1 && earthPillarIndex == 8
        ||
            earthZooIndex == 2 && earthPillarIndex == 9
            ||
                earthZooIndex == 3 && earthPillarIndex == 10
                ||
                    earthZooIndex == 4 && earthPillarIndex == 11
                    ||
                        earthZooIndex == 5 && earthPillarIndex == 12
                        ||
                            earthZooIndex == 6 && earthPillarIndex == 1
                            ||
                                earthZooIndex == 7 && earthPillarIndex == 2
                                ||
                                    earthZooIndex == 8 && earthPillarIndex == 3
                                    ||
                                        earthZooIndex == 9 && earthPillarIndex == 4
                                        ||
                                            earthZooIndex == 10 && earthPillarIndex == 5
                                            ||
                                                earthZooIndex == 11 && earthPillarIndex == 6
                                                ||
                                                    earthZooIndex == 12 && earthPillarIndex == 7;

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

function Pillar addThreeNobleCombinationsStar(Pillar pillar, Zoo earthZooH, Zoo earthZooD, Zoo earthZooM, Zoo earthZooY, Spirit spirit) {

    List<Zoo> zoo = Arrays.asList(Zoo.values());
    Integer earthZooHIndex = zoo.indexOf(earthZooH);
    Integer earthZooDIndex = zoo.indexOf(earthZooD);
    Integer earthZooMIndex = zoo.indexOf(earthZooM);
    Integer earthZooYIndex = zoo.indexOf(earthZooY);

    Zoo earthPillar = pillar.getEarth();
    Integer earthPillarIndex = zoo.indexOf(earthPillar);

    Boolean check =
        earthPillarIndex == earthZooHIndex &&
        (
        earthZooHIndex == 3 && earthZooDIndex == 5 && earthZooMIndex == 9
        ||
        earthZooHIndex == 5 && earthZooDIndex == 9 && earthZooYIndex == 3
        ||
        earthZooHIndex == 9 && earthZooMIndex == 3 && earthZooYIndex == 5
        ||
        earthZooHIndex == 4 && earthZooDIndex == 6 && earthZooMIndex == 7
        ||
        earthZooHIndex == 6 && earthZooDIndex == 7 && earthZooYIndex == 4
        ||
        earthZooHIndex == 7 && earthZooMIndex == 4 && earthZooYIndex == 6
        ||
        earthZooHIndex == 12 && earthZooDIndex == 1 && earthZooMIndex == 10
        ||
        earthZooHIndex == 1 && earthZooDIndex == 10 && earthZooYIndex == 12
        ||
        earthZooHIndex == 10 && earthZooMIndex == 12 && earthZooYIndex == 1
        );

    if(check) { pillar.getSpirit().add(spirit);  }
    return pillar;
}

rule "Add Spirit Angel All"
no-loop true
when
    $natalChart: NatalChart(day != null, hour != null)
    $angelPersolan: Spirit(name == "angelPersolan")
    $angelGenus: Spirit(name == "angelGenus")
    $angelTaiChi: Spirit(name == "angelTaiChi")
    $angelPersonalLife: Spirit(name == "angelPersonalLife")
    $angelHeavenlyKitchen: Spirit(name == "angelHeavenlyKitchen")
    $angelStateStamps: Spirit(name == "angelStateStamps")
    $angelHeavenlyPower: Spirit(name == "angelHeavenlyPower")
    $angelHeavenlyOfficer: Spirit(name == "angelHeavenlyOfficer")
    $angelLiterature: Spirit(name == "angelLiterature")
    $angelCorrectSize: Spirit(name == "angelCorrectSize")
then
   addSpiritAngel($natalChart.getHour(), $natalChart.getDay().getSky(), $angelPersolan);
   addSpiritAngel($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelPersolan);
   addSpiritAngel($natalChart.getYear(), $natalChart.getDay().getSky(), $angelPersolan);

   addSpiritAngel($natalChart.getHour(), $natalChart.getYear().getSky(), $angelGenus);
   addSpiritAngel($natalChart.getDay(), $natalChart.getYear().getSky(), $angelGenus);
   addSpiritAngel($natalChart.getMonth(), $natalChart.getYear().getSky(), $angelGenus);

   addSpiritAngelTaiChi($natalChart.getYear(), $natalChart.getDay().getSky(), $angelTaiChi);

   addSpiritAngelPersonalLife($natalChart.getHour(), $natalChart.getDay().getSky(), $angelPersonalLife);
   addSpiritAngelPersonalLife($natalChart.getDay(), $natalChart.getDay().getSky(), $angelPersonalLife);
   addSpiritAngelPersonalLife($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelPersonalLife);
   addSpiritAngelPersonalLife($natalChart.getYear(), $natalChart.getDay().getSky(), $angelPersonalLife);

   addSpiritAngelHeavenlyKitchen($natalChart.getHour(), $natalChart.getDay().getSky(), $angelHeavenlyKitchen);
   addSpiritAngelHeavenlyKitchen($natalChart.getDay(), $natalChart.getDay().getSky(), $angelHeavenlyKitchen);
   addSpiritAngelHeavenlyKitchen($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelHeavenlyKitchen);
   addSpiritAngelHeavenlyKitchen($natalChart.getYear(), $natalChart.getDay().getSky(), $angelHeavenlyKitchen);

   addSpiritAngelStateStamps($natalChart.getHour(), $natalChart.getDay().getSky(), $angelStateStamps);
   addSpiritAngelStateStamps($natalChart.getDay(), $natalChart.getDay().getSky(), $angelStateStamps);
   addSpiritAngelStateStamps($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelStateStamps);
   addSpiritAngelStateStamps($natalChart.getYear(), $natalChart.getDay().getSky(), $angelStateStamps);

   addSpiritAngelHeavenlyPower($natalChart.getHour(), $natalChart.getDay().getSky(), $angelHeavenlyPower);
   addSpiritAngelHeavenlyPower($natalChart.getDay(), $natalChart.getDay().getSky(), $angelHeavenlyPower);
   addSpiritAngelHeavenlyPower($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelHeavenlyPower);
   addSpiritAngelHeavenlyPower($natalChart.getYear(), $natalChart.getDay().getSky(), $angelHeavenlyPower);

    addSpiritAngelHeavenlyOfficer($natalChart.getHour(), $natalChart.getDay().getSky(), $angelHeavenlyOfficer);
    addSpiritAngelHeavenlyOfficer($natalChart.getDay(), $natalChart.getDay().getSky(), $angelHeavenlyOfficer);
    addSpiritAngelHeavenlyOfficer($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelHeavenlyOfficer);
    addSpiritAngelHeavenlyOfficer($natalChart.getYear(), $natalChart.getDay().getSky(), $angelHeavenlyOfficer);

    addSpiritAngelLiterature($natalChart.getHour(), $natalChart.getDay().getSky(), $angelLiterature);
    addSpiritAngelLiterature($natalChart.getDay(), $natalChart.getDay().getSky(), $angelLiterature);
    addSpiritAngelLiterature($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelLiterature);
    addSpiritAngelLiterature($natalChart.getYear(), $natalChart.getDay().getSky(), $angelLiterature);

    addSpiritAngelCorrectSize($natalChart.getHour(), $natalChart.getDay().getSky(), $angelCorrectSize);
    addSpiritAngelCorrectSize($natalChart.getDay(), $natalChart.getDay().getSky(), $angelCorrectSize);
    addSpiritAngelCorrectSize($natalChart.getMonth(), $natalChart.getDay().getSky(), $angelCorrectSize);
    addSpiritAngelCorrectSize($natalChart.getYear(), $natalChart.getDay().getSky(), $angelCorrectSize);

   update($natalChart);
end;

rule "Add Spirits of Fortune"
no-loop true
when
    $natalChart: NatalChart(day != null, hour != null)
    $heavenlyVirtue: Spirit(name == "heavenlyVirtue")
    $lunarVirtue: Spirit(name == "lunarVirtue")
    $threeMystics: Spirit(name == "threeMystics")
    $helperStar: Spirit(name == "helperStar")
    $dragonStar: Spirit(name == "dragonStar")
    $threeNobleCombinationsStar: Spirit(name == "threeNobleCombinationsStar")
then
    addSpiritHeavenlyVirtue($natalChart.getHour(), $natalChart.getMonth().getEarth(), $heavenlyVirtue);
    addSpiritHeavenlyVirtue($natalChart.getDay(), $natalChart.getMonth().getEarth(), $heavenlyVirtue);
    addSpiritHeavenlyVirtue($natalChart.getMonth(), $natalChart.getMonth().getEarth(), $heavenlyVirtue);
    addSpiritHeavenlyVirtue($natalChart.getYear(), $natalChart.getMonth().getEarth(), $heavenlyVirtue);

    addSpiritLunarVirtue($natalChart.getHour(), $natalChart.getMonth().getEarth(), $lunarVirtue);
    addSpiritLunarVirtue($natalChart.getDay(), $natalChart.getMonth().getEarth(), $lunarVirtue);
    addSpiritLunarVirtue($natalChart.getMonth(), $natalChart.getMonth().getEarth(), $lunarVirtue);
    addSpiritLunarVirtue($natalChart.getYear(), $natalChart.getMonth().getEarth(), $lunarVirtue);

    addSpiritThreeMystics($natalChart.getHour(), 1, $natalChart.getHour().getSky(), $natalChart.getDay().getSky(), $natalChart.getMonth().getSky(), $natalChart.getYear().getSky(), $threeMystics);
    addSpiritThreeMystics($natalChart.getDay(), 2, $natalChart.getHour().getSky(), $natalChart.getDay().getSky(), $natalChart.getMonth().getSky(), $natalChart.getYear().getSky(), $threeMystics);
    addSpiritThreeMystics($natalChart.getMonth(), 3, $natalChart.getHour().getSky(), $natalChart.getDay().getSky(), $natalChart.getMonth().getSky(), $natalChart.getYear().getSky(), $threeMystics);
    addSpiritThreeMystics($natalChart.getYear(), 4, $natalChart.getHour().getSky(), $natalChart.getDay().getSky(), $natalChart.getMonth().getSky(), $natalChart.getYear().getSky(), $threeMystics);

    addSpiritHelperStar($natalChart.getHour(), $natalChart.getDay().getEarth(), $helperStar);
    addSpiritHelperStar($natalChart.getDay(), $natalChart.getDay().getEarth(), $helperStar);
    addSpiritHelperStar($natalChart.getMonth(), $natalChart.getDay().getEarth(), $helperStar);
    addSpiritHelperStar($natalChart.getYear(), $natalChart.getDay().getEarth(), $helperStar);

    addSpiritDragonStar($natalChart.getHour(), $natalChart.getDay().getEarth(), $dragonStar);
    addSpiritDragonStar($natalChart.getDay(), $natalChart.getYear().getEarth(), $dragonStar);
    addSpiritDragonStar($natalChart.getMonth(), $natalChart.getDay().getEarth(), $dragonStar);
    addSpiritDragonStar($natalChart.getYear(), $natalChart.getDay().getEarth(), $dragonStar);

    addThreeNobleCombinationsStar($natalChart.getHour(), $natalChart.getHour().getEarth(), $natalChart.getDay().getEarth(), $natalChart.getMonth().getEarth(), $natalChart.getYear().getEarth(), $threeNobleCombinationsStar);
    addThreeNobleCombinationsStar($natalChart.getDay(), $natalChart.getHour().getEarth(), $natalChart.getDay().getEarth(), $natalChart.getMonth().getEarth(), $natalChart.getYear().getEarth(), $threeNobleCombinationsStar);
    addThreeNobleCombinationsStar($natalChart.getMonth(), $natalChart.getHour().getEarth(), $natalChart.getDay().getEarth(), $natalChart.getMonth().getEarth(), $natalChart.getYear().getEarth(), $threeNobleCombinationsStar);
    addThreeNobleCombinationsStar($natalChart.getYear(), $natalChart.getHour().getEarth(), $natalChart.getDay().getEarth(), $natalChart.getMonth().getEarth(), $natalChart.getYear().getEarth(), $threeNobleCombinationsStar);
    update($natalChart);
end;
